image: ocaml/opam2:alpine-3.7

cache:
  paths:
    - _opam
    - _build

before_script:
  - "grep -q archive-mirrors: ~/.opam/config || echo 'archive-mirrors: [ \"https://opam.ocaml.org/cache\" ]' >> ~/.opam/config"
  - opam repository set-url default https://opam.ocaml.org
  - "[ -d _opam ] || opam switch create . --no-install"
  - "grep -q pre-session-commands: ~/.opam/config || echo 'pre-session-commands: [\"sudo\" \"apk\" \"add\" depexts]' >>~/.opam/config"
  - opam install ./tryocaml.opam.locked -y --deps-only

pages:
  stage: deploy
  script:
    - "eval $(opam env)"
    - make tryocaml
    - mkdir -p public
    - "cp -r www/* public"
  artifacts:
    paths:
      - public
  only:
    - tryocaml

build_image:
  stage: build
  script:
    - docker build -t learn-ocaml --target compilation .
    - "docker run --rm -v $(pwd)/demo-repository:/repository learn-ocaml -- build"
