stages:
  - build
  - image
  - deploy

variables:
  POD_NAME: tryocaml
  CONTAINER_TEST_IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  CONTAINER_RELEASE_IMAGE: $CI_REGISTRY_IMAGE:latest
  POSTGRES_ENABLED: "false"
  OPAMFILE: tryocaml.opam.locked
  ROLLOUT_RESOURCE_TYPE: deployment

prepare:
  stage: .pre
  image: registry.ocamlpro.com/ocamlpro/ocaml-docker-images:4.10
  script:
    - "[ -d _opam ] || opam switch create . --deps-only --locked"
  cache:
    key:
      files:
        - $OPAMFILE
    paths:
      - _opam
  artifacts:
    paths:
      - _opam

build:
  stage: build
  image: registry.ocamlpro.com/ocamlpro/ocaml-docker-images:4.10
  script:
    - opam exec -- make tryocaml
  artifacts:
    paths:
      - www
  only:
    - tryocaml

make-image:
  stage: image
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - |
      echo "\
      {
        \"auths\": {
          \"$CI_REGISTRY\": {
            \"username\":\"$CI_REGISTRY_USER\",
            \"password\":\"$CI_REGISTRY_PASSWORD\"
      }}}
      " > /kaniko/.docker/config.json
    - |
      echo "\
      FROM bitnami/nginx:latest
      COPY www /app
      " > /kaniko/Dockerfile
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile /kaniko/Dockerfile --destination $CONTAINER_TEST_IMAGE
  only:
    - tryocaml

deploy-dev:
  stage: deploy
  image: lwolf/helm-kubectl-docker:latest
#   image: bitnami/kubectl:latest
  environment:
    name: dev
    url: https://tryocaml.k.ocaml.pro
    kubernetes:
      namespace: tryocaml-dev
  before_script:
    # - mkdir -p /etc/deploy
    # - echo $KUBE_CONFIG | base64 -d > /etc/deploy/config
    # - kubectl config set-credentials gitlab-admin --token="${USER_TOKEN}"
    # - kubectl config set-context default --cluster=ovh-ocamlpro --user=gitlab-admin
    # - kubectl config use-context default
# #    - kubectl config use-context XXX
    - helm init --client-only
    # - helm repo add bitnami https://charts.bitnami.com/bitnami
    # - helm repo update
  script:
    - |
      echo "
      image:
        registry: $CI_REGISTRY
        repository: $CI_REGISTRY_IMAGE
        tag: $CI_COMMIT_REF_SLUG
        pullSecrets:
          - name: docker-registry
      ingress:
        hosts:
          - name: $CI_PROJECT_NAME.k.ocaml.pro
        tls:
          - hosts: $CI_PROJECT_NAME.k.ocaml.pro
          - secretName: ${CI_PROJECT_NAME}-tls
      " > deploy.yaml
    - helm install --repo https://charts.bitnami.com/bitnami bitnami/nginx --name=$POD_NAME --namespace tryocaml-dev --atomic -f deploy.yaml
  only:
  - tryocaml
