stages:
  - build
  - deploy

variables:
  CONTAINER_TEST_IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
  CONTAINER_RELEASE_IMAGE: $CI_REGISTRY_IMAGE:latest
  POSTGRES_ENABLED: "false"
  ROLLOUT_RESOURCE_TYPE: deployment

build:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile --destination $CONTAINER_TEST_IMAGE --target server
  only:
    - tryocaml

deploy-auto:
  stage: deploy
  image: "registry.gitlab.com/gitlab-org/cluster-integration/auto-deploy-image:v0.12.1"
  script:
    - auto-deploy check_kube_domain
    - auto-deploy download_chart
    - auto-deploy ensure_namespace
    - auto-deploy initialize_tiller
    - auto-deploy create_secret
    - auto-deploy deploy
  environment:
    name: dev
    url: https://tryocaml.k.ocaml.pro
    kubernetes:
      namespace: tryocaml-dev
  only:
    refs:
      - tryocaml

deploy-dev:
  stage: deploy
  image: lwolf/helm-kubectl-docker:latest
#   image: bitnami/kubectl:latest
  environment:
    name: dev
    url: https://tryocaml.k.ocaml.pro
    kubernetes:
      namespace: tryocaml-dev
  before_script:
    - mkdir -p /etc/deploy
    - echo $KUBE_CONFIG | base64 -d > /etc/deploy/config
#    - kubectl config use-context XXX
    - helm init --client-only
    - helm repo add bitnami https://charts.bitnami.com/bitnami
    - helm repo update
  script:
    - cd deploy/libr-files
    - helm install bitnami/nginx --set image.registry=$CI_REGISTRY,image.repository=$CI_REGISTRY_IMAGE,image.tag=$CI_COMMIT_REF_SLUG,ingress.hosts[0].name=$CI_PROJECT_NAME.k.ocaml.pro,ingress.tls[0].hosts=$CI_PROJECT_NAME.k.ocaml.pro,ingress.tls[0].secretName=${CI_PROJECT_NAME}-tls,image.pullSecrets=gitlab-registry
  only:
  - tryocaml


# deploy-dev:
#   stage: deploy
#   image: bitnami/kubectl:latest
#   environment:
#     name: dev
#     url: https://tryocaml.k.ocaml.pro
#     kubernetes:
#       namespace: tryocaml-dev
#   script:
#     - mkdir -p /.kube
#     - echo -n $KUBE_CONFIG | base64 -d > /.kube/config
#     - kubectl config view
#   only:
#   - tryocaml

